In [1]:
import numpy as np

In [2]:
minha_lista = [1, 2, 3]
minha_lista

[1, 2, 3]

In [3]:
np.array(minha_lista)

array([1, 2, 3])

In [5]:
minha_matriz = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
np.array(minha_matriz)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.zeros(3)

array([0., 0., 0.])

In [12]:
arr = np.zeros((5,5))
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [29]:
arr1 = np.ones((5,5)) * np.random.rand(5,5) * 100
arr1

array([[76.18317904, 17.46037855, 91.92417078, 43.95381392, 87.67829842],
       [30.35284113, 37.53931835, 94.23586154, 11.55355672, 15.45831691],
       [10.97057125, 47.20895143, 12.39573077, 43.22645997, 32.19472985],
       [47.69992181, 30.68562119, 91.01267034, 94.4299621 , 89.60271399],
       [48.33611415, 92.21725542, 42.53474921, 18.03398082, 84.97610383]])

In [22]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [25]:
np.random.rand(2)* 100

array([51.01387884, 90.35945183])

In [26]:
np.random.rand(5,2)

array([[0.28034104, 0.09508395],
       [0.99122561, 0.15932049],
       [0.04358743, 0.32393957],
       [0.30850555, 0.38091452],
       [0.29441983, 0.18684831]])

In [27]:
np.random.randn(2)

array([-1.67847311, -0.36224222])

In [28]:
np.random.randint(1, 100, 10)

array([92, 96, 85,  3, 68, 15, 96, 61, 67, 64])

In [31]:
arr = np.random.rand(25)
arr

array([0.98647157, 0.91548943, 0.92591578, 0.88803027, 0.67513385,
       0.17805077, 0.63476526, 0.78118685, 0.13582789, 0.76866518,
       0.91220042, 0.10394692, 0.23397821, 0.85164076, 0.61518323,
       0.47223548, 0.22698318, 0.76175584, 0.62539465, 0.23612025,
       0.69964393, 0.74023123, 0.61427906, 0.26550292, 0.46391738])

In [32]:
arr = arr.reshape(5,5)
arr

array([[0.98647157, 0.91548943, 0.92591578, 0.88803027, 0.67513385],
       [0.17805077, 0.63476526, 0.78118685, 0.13582789, 0.76866518],
       [0.91220042, 0.10394692, 0.23397821, 0.85164076, 0.61518323],
       [0.47223548, 0.22698318, 0.76175584, 0.62539465, 0.23612025],
       [0.69964393, 0.74023123, 0.61427906, 0.26550292, 0.46391738]])

In [33]:
arr.shape

(5, 5)

In [34]:
arr.max()

0.986471567795074

In [36]:
arr.min()

0.10394691684323953

In [37]:
arr.argmax()

0

Operaçoes Basicas de arrays

In [40]:
arr = np.arange(0, 30, 3)
arr

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [41]:
arr[3]

9

In [48]:
arr[1:5]

array([ 3,  6,  9, 12])

In [92]:
arr= np.arange(50).reshape(5,10)
print(arr[:][:3])

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [55]:
arr2 = arr[:3]
arr2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [93]:
arr2[:] = 100
print(arr)
print(arr2)

UFuncTypeError: ufunc 'add' did not contain a loop with signature matching types (dtype('<U6'), dtype('int32')) -> None

In [63]:
arr3 = arr.copy()
arr3

array([[100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49]])

In [64]:
arr3[1:4,5:]

array([[100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [ 35,  36,  37,  38,  39]])

In [66]:
boll = arr > 50
boll

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [67]:
arr[boll]

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100, 100, 100])

In [69]:
array = np.linspace(0, 100, 30)
array

array([  0.        ,   3.44827586,   6.89655172,  10.34482759,
        13.79310345,  17.24137931,  20.68965517,  24.13793103,
        27.5862069 ,  31.03448276,  34.48275862,  37.93103448,
        41.37931034,  44.82758621,  48.27586207,  51.72413793,
        55.17241379,  58.62068966,  62.06896552,  65.51724138,
        68.96551724,  72.4137931 ,  75.86206897,  79.31034483,
        82.75862069,  86.20689655,  89.65517241,  93.10344828,
        96.55172414, 100.        ])

In [71]:
array = array.reshape(6,5)
array

array([[  0.        ,   3.44827586,   6.89655172,  10.34482759,
         13.79310345],
       [ 17.24137931,  20.68965517,  24.13793103,  27.5862069 ,
         31.03448276],
       [ 34.48275862,  37.93103448,  41.37931034,  44.82758621,
         48.27586207],
       [ 51.72413793,  55.17241379,  58.62068966,  62.06896552,
         65.51724138],
       [ 68.96551724,  72.4137931 ,  75.86206897,  79.31034483,
         82.75862069],
       [ 86.20689655,  89.65517241,  93.10344828,  96.55172414,
        100.        ]])

In [74]:
array[2:4, 3:5]

array([[44.82758621, 48.27586207],
       [62.06896552, 65.51724138]])

Operações com arrays

In [75]:
arr = np.arange(0, 16)

In [76]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [77]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [79]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225])

In [80]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [81]:
arr / arr

C:\Users\daneil\AppData\Local\Temp\ipykernel_18320\3001117470.py:1: RuntimeWarning: invalid value encountered in divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.])

In [82]:
arr -2

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [83]:
arr * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [84]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335])

In [85]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04,
       1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06])

In [86]:
np.std(arr)

4.6097722286464435